---
title: "Student Data analysis of Java Programming"
author: Nischal Shakya
date: 8/23/20
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
getUnique <- function(columnName) {
  return(as.character(unique(columnName)))
}

countGrade <- function(df, value) {
  return(
    df %>% filter(Grade == value) %>% count(Grade)
  )
}

getCountRank <- function(df, value) {
  return(
    df %>% filter(Rank == value) %>% count(Rank)
  )
}

mutateRank <- function(df, columnName) {
  return(df %>% mutate(Rank = case_when(columnName < 40 ~ 'Statisfactory',
                                        columnName >= 40 & columnName < 60 ~ 'Good',
                                        columnName >= 60 & columnName < 80 ~ 'Very Good',
                                        columnName >= 80 & columnName < 95 ~ 'Excellent'))
  )
}

convertRankIntoNumber <- function(df, columnName) {
  return(df %>% mutate(Rank = case_when(columnName < 40 ~ 4,
                                        columnName > 40 & columnName < 60 ~ 3,
                                        columnName >= 60 & columnName < 80 ~ 2,
                                        columnName >= 80 & columnName < 95 ~ 1))
  )
}

sortInAscendingOrder <- function(df, columnName) {
  return(df %>% arrange(columnName))
}

findTop <- function(df, columnName, top = 10) {
  return(df %>% top_n(top, columnName))
}

findTopStudent <- function(df, value, columnName) {
  return(df %>%twoExcellentStudent <- df %>%
  filter(Rank == 'Excellent') %>%
  top_n(2, Total)

twoVeryGoodStudent <- bind_rows(df %>%
                                  filter(Rank == 'Very Good' & Gender == 'M') %>%
                                  top_n(1, Total),
                                df %>%
                                  filter(Rank == 'Very Good' & Gender == 'F') %>%
                                  top_n(1, Total)
)

twoGoodStudent <- bind_rows(df %>%
                              filter(Rank == 'Good' & Gender == 'M') %>%
                              top_n(1, Total),
                            df %>%
                              filter(Rank == 'Good' & Gender == 'F') %>%
                              top_n(1, Total))

twoStatisfactoryStudent <- bind_rows(df %>%
                                       filter(Rank == 'Statisfactory' & Gender == 'M') %>%
                                       top_n(1, Total),
                                     df %>%
                                       filter(Rank == 'Statisfactory' & Gender == 'F') %>%
                                       top_n(1, Total))

general <- bind_rows(twoExcellentStudent, twoVeryGoodStudent, twoGoodStudent, twoStatisfactoryStudent)

general <- general %>% select(Name, Gender, Assignment.Marks.Obtained, Mid.Term.Fifteen.Percent.Marks.Obtained, Lab.Test.Fifteen.Percent.Marks.Obtained, Final.Exam.Forty.Percent.Marks, Total, Rank)

           filter(df$Range == as.character(value)) %>%
           top_n(4, columnName))
}

plotBarGraph <- function(df, x, y, label, xlab, ylab) {
  ggbarplot(df, x = x, y = y, label = label, width = 0.3,
            fill = x, color = x, palette = "jco", xlab = xlab, ylab = ylab)
}

plotStackBar <- function(df, x, y, fill, color, label, xlab, ylab, palette) {
  ggbarplot(df, x = x, y = y,
            fill = fill, color = color, width = 0.6,
            palette = palette,
            label = label,
            position = position_dodge(0.7),
            xlab = xlab,
            ylab = ylab)
}

plotJitter <- function(df, x, y, pch) {
  plot(jitter(x) ~ jitter(y),
       data = df,
       pch = as.character(pch))
}

remove(list = ls())

library('dplyr')

library('ggplot2')

library('ggpubr')

library('fpc')

library('psych')

library('cluster')

source('utils.R')

setwd('/home/nischal/repository/personal/R/nischalshakya15.github.io/work-related-learning')

# Initialized data frame and varibales related to JavaProgrammingOne
df <- read.csv('data-sets/re-modified/JavaProgrammingOne.csv')
df <- mutateRank(df, df$Total)
uniqueGrades <- getUnique(df$Grade)
ranks <- getUnique(df$Rank)
javaOneDfCount <- data.frame()
```
# Java Programming One
## Students on basics of Grade
```{r Student on basics of Grade, echo = FALSE }
for (g in uniqueGrades) {
  javaOneDfCount <- rbind(javaOneDfCount,
                          data.frame(
                                  countGrade(df, g)
                          ))
}

javaOneDfCount <- sortInAscendingOrder(javaOneDfCount, javaOneDfCount$n)

plotBarGraph(df = javaOneDfCount, x = 'Grade', y = 'n',
             label = javaOneDfCount$n, xlab = 'Grade', ylab = 'Number of Student')
```
## Student on basics of Rank
```{r, Student on basics of Rank, echo = FALSE}
javaOneRankWiseDf <- data.frame()

for (r in ranks) {
  javaOneRankWiseDf <- rbind(javaOneRankWiseDf,
                             data.frame(
                                     getCountRank(df, r)
                             ))
}

javaOneRankWiseDf <- sortInAscendingOrder(javaOneRankWiseDf, javaOneRankWiseDf$n)

plotBarGraph(df = javaOneRankWiseDf, x = 'Rank', y = 'n', label = javaOneRankWiseDf$n, xlab = 'Rank', ylab = 'Number of student')

```
## Student on basics of Gender Rank Wise
```{r Student on basics of Gender Rank Wise, echo = FALSE}
javaOneRankWiseGenderDf <- data.frame()

javaOneRankWiseBarChartDf <- data.frame()

for (r in ranks) {
  rankFilter <- df %>% filter(Rank == r)
  femaleRankFilter <- rankFilter %>%
          filter(Gender == "F") %>%
          count(Gender)
  if (length(femaleRankFilter$n) == 0) {
    femaleRankFilter <- data.frame(Gender = "F", n = 0)
  }
  javaOneRankWiseGenderDf <- rbind(javaOneRankWiseGenderDf,
                                   data.frame(
                                           Rank = r,
                                           Male = rankFilter %>%
                                                   filter(Gender == "M") %>%
                                                   count(Gender),
                                           Female = femaleRankFilter
                                   ))
}

javaOneRankWiseGenderDf <- javaOneRankWiseGenderDf %>% select(-c(Male.Gender, Female.Gender))

for (r in ranks) {
  filter <- javaOneRankWiseGenderDf %>% filter(Rank == r)
  javaOneRankWiseBarChartDf <- rbind(javaOneRankWiseBarChartDf,
                                     data.frame(
                                             Rank = rep(r, 2),
                                             Gender = c(rep('Male', 1), rep('Female', 1)),
                                             NoOfStudent = c(filter$Male.n, filter$Female.n)
                                     ))
}

plotStackBar(javaOneRankWiseBarChartDf, x = 'Rank', y = 'NoOfStudent',
             fill = 'Gender', color = 'Gender', palette = 'uchiago',
             label = javaOneRankWiseBarChartDf$NoOfStudent, xlab = 'Rank', ylab = 'No of student')
```
## Top 2 students from each Rank on basics of the Genders
```{r Top 2 students from each rank on basics of the Genders, echo = TRUE}
twoExcellentStudent <- df %>%
        filter(Rank == 'Excellent') %>%
        top_n(2, Total)

twoVeryGoodStudent <- bind_rows(df %>%
                                        filter(Rank == 'Very Good' & Gender == 'M') %>%
                                        top_n(1, Total),
                                df %>%
                                        filter(Rank == 'Very Good' & Gender == 'F') %>%
                                        top_n(1, Total)
)

twoGoodStudent <- bind_rows(df %>%
                                    filter(Rank == 'Good' & Gender == 'M') %>%
                                    top_n(1, Total),
                            df %>%
                                    filter(Rank == 'Good' & Gender == 'F') %>%
                                    top_n(1, Total))

twoStatisfactoryStudent <- bind_rows(df %>%
                                             filter(Rank == 'Statisfactory' & Gender == 'M') %>%
                                             top_n(1, Total),
                                     df %>%
                                             filter(Rank == 'Statisfactory' & Gender == 'F') %>%
                                             top_n(1, Total))

general <- bind_rows(twoExcellentStudent, twoVeryGoodStudent, twoGoodStudent, twoStatisfactoryStudent)

general <- general %>% select(Name, Gender, Assignment.Marks.Obtained, Mid.Term.Fifteen.Percent.Marks.Obtained, Lab.Test.Fifteen.Percent.Marks.Obtained, Final.Exam.Forty.Percent.Marks, Total, Rank)
```